export const products = [
  {
    id: 1,
    title: 'Classic Margherita Pizza',
    description: 'A classic Italian pizza with fresh mozzarella, basil, and tomato sauce, baked to perfection.',
    category: 'vegetarian',
    price: 9.99,
    rating: 4.6,
    stock: 20,
    brand: 'Italian Delight',
    images: ['https://cdn.dummyjson.com/recipe-images/1.webp'],
  },
  {
    id: 2,
    title: 'Vegetarian Stir-Fry',
    description: 'A medley of fresh vegetables stir-fried with tofu and seasoned with soy sauce and ginger.',
    category: 'vegetarian',
    price: 8.99,
    rating: 4.7,
    stock: 15,
    brand: 'Fresh Harvest',
    images: ['https://cdn.dummyjson.com/recipe-images/2.webp'],
  },
  {
    id: 3,
    title: 'Chocolate Chip Cookies',
    description: 'Classic American cookies loaded with chocolate chips, perfect for a sweet treat.',
    category: 'dessert',
    price: 4.99,
    rating: 4.9,
    stock: 30,
    brand: 'Sweet Treats',
    images: ['https://cdn.dummyjson.com/recipe-images/3.webp'],
  },
  {
    id: 4,
    title: 'Chicken Alfredo Pasta',
    description: 'Creamy Alfredo sauce with tender chicken and fettuccine, topped with fresh parsley.',
    category: 'chicken',
    price: 11.99,
    rating: 4.9,
    stock: 12,
    brand: 'Pasta Perfect',
    images: ['https://cdn.dummyjson.com/recipe-images/4.webp'],
  },
  {
    id: 5,
    title: 'Mango Salsa Chicken',
    description: 'Grilled chicken paired with a fresh mango salsa, perfect for a tropical twist on dinner.',
    category: 'chicken',
    price: 13.49,
    rating: 4.9,
    stock: 18,
    brand: 'Tropical Flavors',
    images: ['https://cdn.dummyjson.com/recipe-images/5.webp'],
  },
  {
    id: 6,
    title: 'Quinoa Salad with Avocado',
    description: 'A refreshing quinoa salad with avocado, cherry tomatoes, and feta cheese, tossed in a lemon vinaigrette.',
    category: 'salad',
    price: 7.99,
    rating: 4.4,
    stock: 25,
    brand: 'Healthy Greens',
    images: ['https://cdn.dummyjson.com/recipe-images/6.webp'],
  },
  {
    id: 7,
    title: 'Tomato Basil Bruschetta',
    description: 'Toasted baguette slices topped with diced tomatoes, fresh basil, and balsamic glaze.',
    category: 'vegetarian',
    price: 5.49,
    rating: 4.7,
    stock: 22,
    brand: 'Italian Flavors',
    images: ['https://cdn.dummyjson.com/recipe-images/7.webp'],
  },
  {
    id: 8,
    title: 'Beef and Broccoli Stir-Fry',
    description: 'Tender beef and broccoli cooked in a savory sauce, served over rice.',
    category: 'beef',
    price: 12.49,
    rating: 4.7,
    stock: 15,
    brand: 'Asian Delights',
    images: ['https://cdn.dummyjson.com/recipe-images/8.webp'],
  },
  {
    id: 9,
    title: 'Caprese Salad',
    description: 'A refreshing salad with sliced tomatoes, mozzarella, and fresh basil, drizzled with balsamic glaze.',
    category: 'salad',
    price: 5.99,
    rating: 4.6,
    stock: 20,
    brand: 'Mediterranean Fresh',
    images: ['https://cdn.dummyjson.com/recipe-images/9.webp'],
  },
  {
    id: 10,
    title: 'Shrimp Scampi Pasta',
    description: 'A delicious pasta with shrimp in a buttery garlic sauce, topped with fresh parsley.',
    category: 'chicken',
    price: 14.49,
    rating: 4.3,
    stock: 10,
    brand: 'Seafood Delights',
    images: ['https://cdn.dummyjson.com/recipe-images/10.webp'],
  },
  {
    id: 11,
    title: 'Chicken Biryani',
    description: 'Fragrant basmati rice layered with spiced chicken, tomatoes, and aromatic herbs.',
    category: 'chicken',
    price: 13.99,
    rating: 5.0,
    stock: 18,
    brand: 'Spice Haven',
    images: ['https://cdn.dummyjson.com/recipe-images/11.webp'],
  },
  {
    id: 12,
    title: 'Chicken Karahi',
    description: 'Spiced chicken cooked in a tomato-based gravy, garnished with coriander and served with naan.',
    category: 'chicken',
    price: 12.99,
    rating: 4.8,
    stock: 20,
    brand: 'Pakistani Flavors',
    images: ['https://cdn.dummyjson.com/recipe-images/12.webp'],
  },
  {
    id: 13,
    title: 'Aloo Keema',
    description: 'Ground beef and diced potatoes simmered with spices, served with naan or rice.',
    category: 'beef',
    price: 11.99,
    rating: 4.6,
    stock: 22,
    brand: 'Pakistani Flavors',
    images: ['https://cdn.dummyjson.com/recipe-images/13.webp'],
  },
  {
    id: 14,
    title: 'Chapli Kebabs',
    description: 'Flat, spiced beef patties, perfect for pairing with naan or mint chutney.',
    category: 'beef',
    price: 10.99,
    rating: 4.7,
    stock: 25,
    brand: 'Asian Flavors',
    images: ['https://cdn.dummyjson.com/recipe-images/14.webp'],
  },
  {
    id: 15,
    title: 'Saag with Makki di Roti',
    description: 'Mustard greens and spinach served with golden corn flatbread.',
    category: 'vegetarian',
    price: 8.49,
    rating: 4.3,
    stock: 15,
    brand: 'Punjabi Cuisine',
    images: ['https://cdn.dummyjson.com/recipe-images/15.webp'],
  },
  {
    id: 16,
    title: 'Japanese Ramen Soup',
    description: 'Rich and flavorful ramen soup with chicken, mushrooms, and boiled eggs.',
    category: 'chicken',
    price: 13.49,
    rating: 4.9,
    stock: 10,
    brand: 'Asian Delights',
    images: ['https://cdn.dummyjson.com/recipe-images/16.webp'],
  },
  {
    id: 17,
    title: 'Moroccan Chickpea Tagine',
    description: 'Slow-cooked chickpeas with spices and vegetables, served with couscous.',
    category: 'vegetarian',
    price: 9.99,
    rating: 4.5,
    stock: 18,
    brand: 'Mediterranean Flavors',
    images: ['https://cdn.dummyjson.com/recipe-images/17.webp'],
  },
  {
    id: 18,
    title: 'Korean Bibimbap',
    description: 'A rice bowl topped with beef bulgogi, vegetables, and a fried egg, served with gochujang sauce.',
    category: 'beef',
    price: 14.99,
    rating: 4.9,
    stock: 12,
    brand: 'Asian Delights',
    images: ['https://cdn.dummyjson.com/recipe-images/18.webp'],
  },
  {
    id: 19,
    title: 'Greek Moussaka',
    description: 'Layered eggplants, ground meat, and béchamel sauce baked to golden perfection.',
    category: 'beef',
    price: 13.99,
    rating: 4.3,
    stock: 15,
    brand: 'Greek Delights',
    images: ['https://cdn.dummyjson.com/recipe-images/19.webp'],
  },
  {
    id: 20,
    title: 'Butter Chicken',
    description: 'Rich and creamy chicken curry made with tomato and butter sauce, served with naan.',
    category: 'chicken',
    price: 14.49,
    rating: 4.5,
    stock: 18,
    brand: 'Indian Cuisine',
    images: ['https://cdn.dummyjson.com/recipe-images/20.webp'],
  },
  {
    id: 21,
    title: 'Thai Green Curry',
    description: 'Fragrant green curry with chicken, eggplants, and fresh basil leaves, served over jasmine rice.',
    category: 'chicken',
    price: 13.49,
    rating: 4.2,
    stock: 20,
    brand: 'Asian Delights',
    images: ['https://cdn.dummyjson.com/recipe-images/21.webp'],
  },
  {
    id: 23,
    title: 'Italian Tiramisu',
    description: 'A classic Italian dessert made with layers of espresso-soaked ladyfingers, mascarpone, and cocoa powder.',
    category: 'dessert',
    price: 8.99,
    rating: 4.6,
    stock: 15,
    brand: 'Dolce Vita',
    images: ['https://cdn.dummyjson.com/recipe-images/23.webp'],
  },
  {
    id: 25,
    title: 'Blueberry Banana Smoothie',
    description: 'A refreshing and nutritious smoothie made with blueberries, banana, Greek yogurt, and almond milk.',
    category: 'beverage',
    price: 5.49,
    rating: 4.8,
    stock: 25,
    brand: 'Smoothie Bliss',
    images: ['https://cdn.dummyjson.com/recipe-images/25.webp'],
  },
];
